import { db, sqlite } from "./index.js";
import { surahs, users } from "./schema.js";
import bcrypt from "bcryptjs";
import fs from "fs";
import path from "path";

// Surah data
const surahData = [
  {
    id: 1,
    name: "Al-Fatihah",
    arabicName: "الفاتحة",
    totalAyahs: 7,
    juz: '["1"]',
  },
  {
    id: 2,
    name: "Al-Baqarah",
    arabicName: "البقرة",
    totalAyahs: 286,
    juz: '["1","2","3"]',
  },
  {
    id: 3,
    name: "Ali 'Imran",
    arabicName: "آل عمران",
    totalAyahs: 200,
    juz: '["3","4"]',
  },
  {
    id: 4,
    name: "An-Nisa",
    arabicName: "النساء",
    totalAyahs: 176,
    juz: '["4","5","6"]',
  },
  {
    id: 5,
    name: "Al-Ma'idah",
    arabicName: "المائدة",
    totalAyahs: 120,
    juz: '["6","7"]',
  },
  {
    id: 6,
    name: "Al-An'am",
    arabicName: "الأنعام",
    totalAyahs: 165,
    juz: '["7","8"]',
  },
  {
    id: 7,
    name: "Al-A'raf",
    arabicName: "الأعراف",
    totalAyahs: 206,
    juz: '["8","9"]',
  },
  {
    id: 8,
    name: "Al-Anfal",
    arabicName: "الأنفال",
    totalAyahs: 75,
    juz: '["9","10"]',
  },
  {
    id: 9,
    name: "At-Tawbah",
    arabicName: "التوبة",
    totalAyahs: 129,
    juz: '["10","11"]',
  },
  { id: 10, name: "Yunus", arabicName: "يونس", totalAyahs: 109, juz: '["11"]' },
  {
    id: 11,
    name: "Hud",
    arabicName: "هود",
    totalAyahs: 123,
    juz: '["11","12"]',
  },
  {
    id: 12,
    name: "Yusuf",
    arabicName: "يوسف",
    totalAyahs: 111,
    juz: '["12","13"]',
  },
  {
    id: 13,
    name: "Ar-Ra'd",
    arabicName: "الرعد",
    totalAyahs: 43,
    juz: '["13"]',
  },
  {
    id: 14,
    name: "Ibrahim",
    arabicName: "إبراهيم",
    totalAyahs: 52,
    juz: '["13"]',
  },
  {
    id: 15,
    name: "Al-Hijr",
    arabicName: "الحجر",
    totalAyahs: 99,
    juz: '["14"]',
  },
  {
    id: 16,
    name: "An-Nahl",
    arabicName: "النحل",
    totalAyahs: 128,
    juz: '["14"]',
  },
  {
    id: 17,
    name: "Al-Isra",
    arabicName: "الإسراء",
    totalAyahs: 111,
    juz: '["15"]',
  },
  {
    id: 18,
    name: "Al-Kahf",
    arabicName: "الكهف",
    totalAyahs: 110,
    juz: '["15","16"]',
  },
  { id: 19, name: "Maryam", arabicName: "مريم", totalAyahs: 98, juz: '["16"]' },
  { id: 20, name: "Ta-Ha", arabicName: "طه", totalAyahs: 135, juz: '["16"]' },
  {
    id: 21,
    name: "Al-Anbiya",
    arabicName: "الأنبياء",
    totalAyahs: 112,
    juz: '["17"]',
  },
  {
    id: 22,
    name: "Al-Hajj",
    arabicName: "الحج",
    totalAyahs: 78,
    juz: '["17"]',
  },
  {
    id: 23,
    name: "Al-Mu'minun",
    arabicName: "المؤمنون",
    totalAyahs: 118,
    juz: '["18"]',
  },
  {
    id: 24,
    name: "An-Nur",
    arabicName: "النور",
    totalAyahs: 64,
    juz: '["18"]',
  },
  {
    id: 25,
    name: "Al-Furqan",
    arabicName: "الفرقان",
    totalAyahs: 77,
    juz: '["18","19"]',
  },
  {
    id: 26,
    name: "Ash-Shu'ara",
    arabicName: "الشعراء",
    totalAyahs: 227,
    juz: '["19"]',
  },
  {
    id: 27,
    name: "An-Naml",
    arabicName: "النمل",
    totalAyahs: 93,
    juz: '["19","20"]',
  },
  {
    id: 28,
    name: "Al-Qasas",
    arabicName: "القصص",
    totalAyahs: 88,
    juz: '["20"]',
  },
  {
    id: 29,
    name: "Al-'Ankabut",
    arabicName: "العنكبوت",
    totalAyahs: 69,
    juz: '["20","21"]',
  },
  {
    id: 30,
    name: "Ar-Rum",
    arabicName: "الروم",
    totalAyahs: 60,
    juz: '["21"]',
  },
  {
    id: 31,
    name: "Luqman",
    arabicName: "لقمان",
    totalAyahs: 34,
    juz: '["21"]',
  },
  {
    id: 32,
    name: "As-Sajdah",
    arabicName: "السجدة",
    totalAyahs: 30,
    juz: '["21"]',
  },
  {
    id: 33,
    name: "Al-Ahzab",
    arabicName: "الأحزاب",
    totalAyahs: 73,
    juz: '["21","22"]',
  },
  { id: 34, name: "Saba", arabicName: "سبأ", totalAyahs: 54, juz: '["22"]' },
  { id: 35, name: "Fatir", arabicName: "فاطر", totalAyahs: 45, juz: '["22"]' },
  {
    id: 36,
    name: "Ya-Sin",
    arabicName: "يس",
    totalAyahs: 83,
    juz: '["22","23"]',
  },
  {
    id: 37,
    name: "As-Saffat",
    arabicName: "الصافات",
    totalAyahs: 182,
    juz: '["23"]',
  },
  { id: 38, name: "Sad", arabicName: "ص", totalAyahs: 88, juz: '["23"]' },
  {
    id: 39,
    name: "Az-Zumar",
    arabicName: "الزمر",
    totalAyahs: 75,
    juz: '["23","24"]',
  },
  { id: 40, name: "Ghafir", arabicName: "غافر", totalAyahs: 85, juz: '["24"]' },
  {
    id: 41,
    name: "Fussilat",
    arabicName: "فصلت",
    totalAyahs: 54,
    juz: '["24","25"]',
  },
  {
    id: 42,
    name: "Ash-Shura",
    arabicName: "الشورى",
    totalAyahs: 53,
    juz: '["25"]',
  },
  {
    id: 43,
    name: "Az-Zukhruf",
    arabicName: "الزخرف",
    totalAyahs: 89,
    juz: '["25"]',
  },
  {
    id: 44,
    name: "Ad-Dukhan",
    arabicName: "الدخان",
    totalAyahs: 59,
    juz: '["25"]',
  },
  {
    id: 45,
    name: "Al-Jathiyah",
    arabicName: "الجاثية",
    totalAyahs: 37,
    juz: '["25"]',
  },
  {
    id: 46,
    name: "Al-Ahqaf",
    arabicName: "الأحقاف",
    totalAyahs: 35,
    juz: '["26"]',
  },
  {
    id: 47,
    name: "Muhammad",
    arabicName: "محمد",
    totalAyahs: 38,
    juz: '["26"]',
  },
  {
    id: 48,
    name: "Al-Fath",
    arabicName: "الفتح",
    totalAyahs: 29,
    juz: '["26"]',
  },
  {
    id: 49,
    name: "Al-Hujurat",
    arabicName: "الحجرات",
    totalAyahs: 18,
    juz: '["26"]',
  },
  { id: 50, name: "Qaf", arabicName: "ق", totalAyahs: 45, juz: '["26"]' },
  {
    id: 51,
    name: "Adh-Dhariyat",
    arabicName: "الذاريات",
    totalAyahs: 60,
    juz: '["26","27"]',
  },
  {
    id: 52,
    name: "At-Tur",
    arabicName: "الطور",
    totalAyahs: 49,
    juz: '["27"]',
  },
  {
    id: 53,
    name: "An-Najm",
    arabicName: "النجم",
    totalAyahs: 62,
    juz: '["27"]',
  },
  {
    id: 54,
    name: "Al-Qamar",
    arabicName: "القمر",
    totalAyahs: 55,
    juz: '["27"]',
  },
  {
    id: 55,
    name: "Ar-Rahman",
    arabicName: "الرحمن",
    totalAyahs: 78,
    juz: '["27"]',
  },
  {
    id: 56,
    name: "Al-Waqi'ah",
    arabicName: "الواقعة",
    totalAyahs: 96,
    juz: '["27"]',
  },
  {
    id: 57,
    name: "Al-Hadid",
    arabicName: "الحديد",
    totalAyahs: 29,
    juz: '["27"]',
  },
  {
    id: 58,
    name: "Al-Mujadila",
    arabicName: "المجادلة",
    totalAyahs: 22,
    juz: '["28"]',
  },
  {
    id: 59,
    name: "Al-Hashr",
    arabicName: "الحشر",
    totalAyahs: 24,
    juz: '["28"]',
  },
  {
    id: 60,
    name: "Al-Mumtahanah",
    arabicName: "الممتحنة",
    totalAyahs: 13,
    juz: '["28"]',
  },
  {
    id: 61,
    name: "As-Saff",
    arabicName: "الصف",
    totalAyahs: 14,
    juz: '["28"]',
  },
  {
    id: 62,
    name: "Al-Jumu'ah",
    arabicName: "الجمعة",
    totalAyahs: 11,
    juz: '["28"]',
  },
  {
    id: 63,
    name: "Al-Munafiqun",
    arabicName: "المنافقون",
    totalAyahs: 11,
    juz: '["28"]',
  },
  {
    id: 64,
    name: "At-Taghabun",
    arabicName: "التغابن",
    totalAyahs: 18,
    juz: '["28"]',
  },
  {
    id: 65,
    name: "At-Talaq",
    arabicName: "الطلاق",
    totalAyahs: 12,
    juz: '["28"]',
  },
  {
    id: 66,
    name: "At-Tahrim",
    arabicName: "التحريم",
    totalAyahs: 12,
    juz: '["28"]',
  },
  {
    id: 67,
    name: "Al-Mulk",
    arabicName: "الملك",
    totalAyahs: 30,
    juz: '["29"]',
  },
  {
    id: 68,
    name: "Al-Qalam",
    arabicName: "القلم",
    totalAyahs: 52,
    juz: '["29"]',
  },
  {
    id: 69,
    name: "Al-Haqqah",
    arabicName: "الحاقة",
    totalAyahs: 52,
    juz: '["29"]',
  },
  {
    id: 70,
    name: "Al-Ma'arij",
    arabicName: "المعارج",
    totalAyahs: 44,
    juz: '["29"]',
  },
  { id: 71, name: "Nuh", arabicName: "نوح", totalAyahs: 28, juz: '["29"]' },
  {
    id: 72,
    name: "Al-Jinn",
    arabicName: "الجن",
    totalAyahs: 28,
    juz: '["29"]',
  },
  {
    id: 73,
    name: "Al-Muzzammil",
    arabicName: "المزمل",
    totalAyahs: 20,
    juz: '["29"]',
  },
  {
    id: 74,
    name: "Al-Muddaththir",
    arabicName: "المدثر",
    totalAyahs: 56,
    juz: '["29"]',
  },
  {
    id: 75,
    name: "Al-Qiyamah",
    arabicName: "القيامة",
    totalAyahs: 40,
    juz: '["29"]',
  },
  {
    id: 76,
    name: "Al-Insan",
    arabicName: "الإنسان",
    totalAyahs: 31,
    juz: '["29"]',
  },
  {
    id: 77,
    name: "Al-Mursalat",
    arabicName: "المرسلات",
    totalAyahs: 50,
    juz: '["29"]',
  },
  {
    id: 78,
    name: "An-Naba",
    arabicName: "النبأ",
    totalAyahs: 40,
    juz: '["30"]',
  },
  {
    id: 79,
    name: "An-Nazi'at",
    arabicName: "النازعات",
    totalAyahs: 46,
    juz: '["30"]',
  },
  { id: 80, name: "'Abasa", arabicName: "عبس", totalAyahs: 42, juz: '["30"]' },
  {
    id: 81,
    name: "At-Takwir",
    arabicName: "التكوير",
    totalAyahs: 29,
    juz: '["30"]',
  },
  {
    id: 82,
    name: "Al-Infitar",
    arabicName: "الانفطار",
    totalAyahs: 19,
    juz: '["30"]',
  },
  {
    id: 83,
    name: "Al-Mutaffifin",
    arabicName: "المطففين",
    totalAyahs: 36,
    juz: '["30"]',
  },
  {
    id: 84,
    name: "Al-Inshiqaq",
    arabicName: "الانشقاق",
    totalAyahs: 25,
    juz: '["30"]',
  },
  {
    id: 85,
    name: "Al-Buruj",
    arabicName: "البروج",
    totalAyahs: 22,
    juz: '["30"]',
  },
  {
    id: 86,
    name: "At-Tariq",
    arabicName: "الطارق",
    totalAyahs: 17,
    juz: '["30"]',
  },
  {
    id: 87,
    name: "Al-A'la",
    arabicName: "الأعلى",
    totalAyahs: 19,
    juz: '["30"]',
  },
  {
    id: 88,
    name: "Al-Ghashiyah",
    arabicName: "الغاشية",
    totalAyahs: 26,
    juz: '["30"]',
  },
  {
    id: 89,
    name: "Al-Fajr",
    arabicName: "الفجر",
    totalAyahs: 30,
    juz: '["30"]',
  },
  {
    id: 90,
    name: "Al-Balad",
    arabicName: "البلد",
    totalAyahs: 20,
    juz: '["30"]',
  },
  {
    id: 91,
    name: "Ash-Shams",
    arabicName: "الشمس",
    totalAyahs: 15,
    juz: '["30"]',
  },
  {
    id: 92,
    name: "Al-Layl",
    arabicName: "الليل",
    totalAyahs: 21,
    juz: '["30"]',
  },
  {
    id: 93,
    name: "Ad-Duha",
    arabicName: "الضحى",
    totalAyahs: 11,
    juz: '["30"]',
  },
  {
    id: 94,
    name: "Ash-Sharh",
    arabicName: "الشرح",
    totalAyahs: 8,
    juz: '["30"]',
  },
  { id: 95, name: "At-Tin", arabicName: "التين", totalAyahs: 8, juz: '["30"]' },
  {
    id: 96,
    name: "Al-'Alaq",
    arabicName: "العلق",
    totalAyahs: 19,
    juz: '["30"]',
  },
  {
    id: 97,
    name: "Al-Qadr",
    arabicName: "القدر",
    totalAyahs: 5,
    juz: '["30"]',
  },
  {
    id: 98,
    name: "Al-Bayyinah",
    arabicName: "البينة",
    totalAyahs: 8,
    juz: '["30"]',
  },
  {
    id: 99,
    name: "Az-Zalzalah",
    arabicName: "الزلزلة",
    totalAyahs: 8,
    juz: '["30"]',
  },
  {
    id: 100,
    name: "Al-'Adiyat",
    arabicName: "العاديات",
    totalAyahs: 11,
    juz: '["30"]',
  },
  {
    id: 101,
    name: "Al-Qari'ah",
    arabicName: "القارعة",
    totalAyahs: 11,
    juz: '["30"]',
  },
  {
    id: 102,
    name: "At-Takathur",
    arabicName: "التكاثر",
    totalAyahs: 8,
    juz: '["30"]',
  },
  {
    id: 103,
    name: "Al-'Asr",
    arabicName: "العصر",
    totalAyahs: 3,
    juz: '["30"]',
  },
  {
    id: 104,
    name: "Al-Humazah",
    arabicName: "الهمزة",
    totalAyahs: 9,
    juz: '["30"]',
  },
  {
    id: 105,
    name: "Al-Fil",
    arabicName: "الفيل",
    totalAyahs: 5,
    juz: '["30"]',
  },
  {
    id: 106,
    name: "Quraysh",
    arabicName: "قريش",
    totalAyahs: 4,
    juz: '["30"]',
  },
  {
    id: 107,
    name: "Al-Ma'un",
    arabicName: "الماعون",
    totalAyahs: 7,
    juz: '["30"]',
  },
  {
    id: 108,
    name: "Al-Kawthar",
    arabicName: "الكوثر",
    totalAyahs: 3,
    juz: '["30"]',
  },
  {
    id: 109,
    name: "Al-Kafirun",
    arabicName: "الكافرون",
    totalAyahs: 6,
    juz: '["30"]',
  },
  {
    id: 110,
    name: "An-Nasr",
    arabicName: "النصر",
    totalAyahs: 3,
    juz: '["30"]',
  },
  {
    id: 111,
    name: "Al-Masad",
    arabicName: "المسد",
    totalAyahs: 5,
    juz: '["30"]',
  },
  {
    id: 112,
    name: "Al-Ikhlas",
    arabicName: "الإخلاص",
    totalAyahs: 4,
    juz: '["30"]',
  },
  {
    id: 113,
    name: "Al-Falaq",
    arabicName: "الفلق",
    totalAyahs: 5,
    juz: '["30"]',
  },
  {
    id: 114,
    name: "An-Nas",
    arabicName: "الناس",
    totalAyahs: 6,
    juz: '["30"]',
  },
];

async function seed() {
  console.log("🌱 Starting database seed...\n");

  try {
    // Seed surahs
    console.log("📖 Seeding Surahs...");
    for (const surah of surahData) {
      await db.insert(surahs).values(surah).onConflictDoNothing();
    }
    console.log("✅ Surahs seeded successfully\n");

    // Seed default admin user
    console.log("👤 Creating default admin user...");
    const hashedPassword = await bcrypt.hash("admin123", 12);

    await db
      .insert(users)
      .values({
        name: "Admin",
        email: "admin@tahfidz.app",
        password: hashedPassword,
        role: "admin",
        isActive: true,
      })
      .onConflictDoNothing();
    console.log("✅ Default admin created: admin@tahfidz.app / admin123\n");

    // Create sample teacher
    console.log("👨‍🏫 Creating sample teacher...");
    const teacherPassword = await bcrypt.hash("teacher123", 12);
    await db
      .insert(users)
      .values({
        name: "Ustadz Ahmad",
        email: "teacher@tahfidz.app",
        password: teacherPassword,
        role: "teacher",
        isActive: true,
      })
      .onConflictDoNothing();
    console.log(
      "✅ Sample teacher created: teacher@tahfidz.app / teacher123\n",
    );

    console.log("🎉 Database seed completed successfully!");
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }
}

seed();
